version: '3.3'

services:
  discord-bot:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: discord-bot
    image: discord-bot
    working_dir: /usr/src/app
    networks:
      - node-network
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ../:/usr/src/app
    command: bash "/usr/src/app/start.sh"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db
    networks:
      - node-network
    command: mongod --dbpath /data/db
  
networks:
  node-network:
    driver: bridge

